const styles = {
  page: {
    width: "100%",
  },
  detailCard: {
    bgcolor: "background.paper",
    borderRadius: 2,
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  detailCardBody: {
    p: 4,
  },
  backBtn: {
    color: "#9aa0a6",
    textTransform: "none",
    fontSize: 14,
    pl: 0,
    "&:hover": { bgcolor: "transparent", color: "#5f6368" },
    mb: 3,
  },
  container: {
    display: "flex",
    flexDirection: "column",
    gap: { xs: 3, md: 5 },
    mt: 2,
  },
  avatarWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    minWidth: 160,
  },
  avatar: {
    width: 110,
    height: 110,
    bgcolor: "#3aa6a0",
    mb: 1.5,
  },
  name: {
    fontWeight: 700,
    color: "#5b2b1a",
    fontSize: 18,
    lineHeight: 1.2,
  },
  role: {
    color: "#9aa0a6",
    fontSize: 14,
    mt: 0.5,
  },
  formGrid: {
    flex: 1,
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr" },
    columnGap: 2,
    rowGap: 2,
  },
  fieldFull: {
    gridColumn: { xs: "1", sm: "1 / -1" },
  },
  label: {
    fontSize: 14,
    color: "#202124",
    mb: 0.75,
    fontWeight: 500,
  },
  input: {
    "& .MuiOutlinedInput-root": {
      bgcolor: "#f3f5f7",
      borderRadius: "8px",
      "& fieldset": { border: "none" },
      "&:hover fieldset": { border: "none" },
      "&.Mui-focused fieldset": { border: "1px solid #3aa6a0" },
    },
    "& .MuiOutlinedInput-input": {
      py: 1.25,
      fontSize: 14,
    },
  },
  docsHeader: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    mb: 2,
    color: "#202124",
    fontWeight: 500,
    fontSize: 15,
  },
  docCard: {
    bgcolor: "#e6ebf2",
    borderRadius: "8px",
    height: 150,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#202124",
    fontSize: 14,
    mb: 2,
  },
  documentsList: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 1.5,
  },
  documentItem: {
    position: "relative",
    overflow: "hidden",
    borderRadius: "8px",
    bgcolor: "#ffffff",
    border: "1px solid #e3e8ef",
    "&:hover .doc-overlay": {
      opacity: 1,
      pointerEvents: "auto",
    },
  },
  pdfCard: {
    minHeight: 180,
    p: 2,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 1,
    textAlign: "center",
  },
  pdfIcon: {
    color: "#ef4444",
    fontSize: 42,
  },
  pdfName: {
    fontSize: 13,
    color: "#334155",
    wordBreak: "break-word",
  },
  documentOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(15, 23, 42, 0.35)",
    opacity: 0,
    pointerEvents: "none",
    transition: "opacity 0.18s ease",
  },
  overlayViewBtn: {
    textTransform: "none",
    fontSize: 13,
    minWidth: 96,
    borderRadius: "8px",
    bgcolor: "#ffffff",
    color: "#334155",
    border: "1px solid #cbd5e1",
    boxShadow: "0 4px 12px rgba(0,0,0,0.16)",
    "&:hover": {
      bgcolor: "#f8fafc",
      borderColor: "#94a3b8",
    },
  },
  documentImage: {
    width: "100%",
    height: 180,
    objectFit: "contain",
    objectPosition: "center",
    backgroundColor: "#ffffff",
    display: "block",
  },
  previewImage: {
    width: "100%",
    maxHeight: "75vh",
    objectFit: "contain",
    display: "block",
    backgroundColor: "#fff",
  },
  previewPdf: {
    width: "100%",
    height: "75vh",
    border: 0,
    backgroundColor: "#fff",
  },
  emptyDocuments: {
    color: "#5f6368",
    fontSize: 14,
  },
  divider: {
    my: 3,
  },
  actions: {
    display: "flex",
    gap: 2,
    justifyContent: "center",
    mt: 2,
  },
  approveBtn: {
    flex: 1,
    maxWidth: 280,
    bgcolor: "#22c55e",
    color: "#fff",
    textTransform: "none",
    fontWeight: 600,
    fontSize: 15,
    py: 1.25,
    borderRadius: "8px",
    boxShadow: "none",
    "&:hover": { bgcolor: "#16a34a", boxShadow: "none" },
  },
  rejectBtn: {
    flex: 1,
    maxWidth: 280,
    bgcolor: "#fde2e2",
    color: "#e53935",
    textTransform: "none",
    fontWeight: 600,
    fontSize: 15,
    py: 1.25,
    borderRadius: "8px",
    boxShadow: "none",
    "&:hover": { bgcolor: "#fbcdcd", boxShadow: "none" },
  },
};

export default styles;
